apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  bootstrapServers: eventstreams-kafka-bootstrap.eventstreams.svc:9093
  authentication:
    passwordSecret:
      password: password
      secretName: kafka-connect-user
    type: scram-sha-512
    username: kafka-connect-user
  config:
    group.id: connect-cluster
    config.storage.replication.factor: 1
    config.storage.topic: connect-cluster-configs  
    offset.storage.replication.factor: 1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: 1
    status.storage.topic: connect-cluster-status
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  template:
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      metadata:
        annotations:        
          productVersion: 11.3.2
          productID: 46c2d3697ae4406d9157c58de4b66dcc
          productChargedContainers: kafka-connect-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Automation Non-Production
          eventstreams.production.type: EventAutomationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
      imagePullSecrets: []
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/eventstreams/mq-source-and-datagen-connectors:0.0.1
    plugins:
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.1/kafka-connect-loosehangerjeans-source-0.0.1-jar-with-dependencies.jar
      - name: mq-source
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v1.3.3/kafka-connect-mq-source-1.3.3-jar-with-dependencies.jar
