apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: liberty-operands
  labels:
    group: applications
spec:
  generators:
  - list:
      elements:
        - name: liberty
          namespace: liberty
          sync-wave: "200"
        - name: mq
          namespace: mq
          sync-wave: "200"
        #- name: eventstreams
        #  namespace: eventstreams
        #  sync-wave: "200"
        - name: ci
          namespace: liberty
          sync-wave: "200"
        - name: reloader
          namespace: mq
          sync-wave: "200"
        - name: openshift-monitoring
          namespace: openshift-monitoring
          sync-wave: "200"
        - name: openshift-logging
          namespace: openshift-logging
          sync-wave: "200"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: liberty
      source:
        path: 'envs/odf/nonprod/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true