apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: liberty
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  orphanedResources:
    ignore:
    - kind: PersistentVolumeClaim
      name: data-eventstreams-kafka-0
    - kind: PersistentVolumeClaim
      name: data-eventstreams-zookeeper-0
