apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eventprocessing-ui-certificate
spec:
  dnsNames:
    - ibm-event-processing-ibm-ep-rt-eventprocessing.apps.6639dd1691acca001e043026.cloud.techzone.ibm.com
